"use client";

import { Card } from "@/components/ui/card";
import { InfoTip } from "@/components/ui/info-tip";
import type { ApoCycleStats } from "@/types";

function formatDateTime(dateStr: string | null): string {
  if (!dateStr) return "Never";
  return new Date(dateStr).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

interface CycleStatusProps {
  stats: ApoCycleStats;
}

export function CycleStatus({ stats }: CycleStatusProps) {
  return (
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
      <Card className="border-slate-800 bg-slate-900/50 p-4">
        <p className="flex items-center text-xs text-slate-500 uppercase tracking-wide">
          Last Run
          <InfoTip text="Timestamp of the most recent APO cron execution. The cron job scans agent logs for failure patterns and generates new skill-improvement proposals. If this is stale, check that the cron is scheduled correctly." />
        </p>
        <p className="text-sm font-semibold text-slate-100 mt-1">
          {formatDateTime(stats.lastRun)}
        </p>
      </Card>

      <Card className="border-slate-800 bg-slate-900/50 p-4">
        <p className="flex items-center text-xs text-slate-500 uppercase tracking-wide">
          Total Proposals
          <InfoTip text="Cumulative count of all skill-improvement proposals ever generated by the APO, including both pending and archived. Reflects the total volume of optimizations the system has identified." />
        </p>
        <p className="text-3xl font-bold text-slate-100 mt-1">
          {stats.totalProposals}
        </p>
      </Card>

      <Card className="border-slate-800 bg-slate-900/50 p-4">
        <p className="flex items-center text-xs text-slate-500 uppercase tracking-wide">
          Pending
          <InfoTip text="Proposals awaiting your review. Each one suggests a specific edit to a skill file to improve agent behavior. Review them in the Proposals list below and accept or dismiss." />
        </p>
        <p className="text-3xl font-bold text-amber-400 mt-1">
          {stats.pendingProposals}
        </p>
      </Card>

      <Card className="border-slate-800 bg-slate-900/50 p-4">
        <p className="flex items-center text-xs text-slate-500 uppercase tracking-wide">
          Archived
          <InfoTip text="Proposals that have been accepted (applied to skill files) or dismissed. Archived proposals are kept for audit history so you can track what optimizations have been applied over time." />
        </p>
        <p className="text-3xl font-bold text-slate-400 mt-1">
          {stats.archivedProposals}
        </p>
      </Card>
    </div>
  );
}
