"use client";

import { Card } from "@/components/ui/card";
import { InfoTip } from "@/components/ui/info-tip";
import type { ApoCycleStats } from "@/types";

function formatDateTime(dateStr: string | null): string {
  if (!dateStr) return "Never";
  return new Date(dateStr).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

interface CycleStatusProps {
  stats: ApoCycleStats;
}

export function CycleStatus({ stats }: CycleStatusProps) {
  const stages = [
    {
      label: "Waiting",
      count: stats.pendingProposals,
      tone: "bg-amber-400",
      description: "Needs review",
    },
    {
      label: "Queued",
      count: stats.approvedProposals,
      tone: "bg-cyan-400",
      description: "Approved for worker",
    },
    {
      label: "Implemented",
      count: stats.archivedProposals,
      tone: "bg-emerald-400",
      description: "Archived history",
    },
  ];

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
        <Card className="border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
          <p className="flex items-center text-xs text-stone-500 uppercase tracking-wide">
            Last Run
            <InfoTip text="Timestamp of the most recent APO cron execution. The cron job scans agent logs for failure patterns and generates new skill-improvement proposals. If this is stale, check that the cron is scheduled correctly." />
          </p>
          <p className="mt-1 text-sm font-semibold text-slate-950">
            {formatDateTime(stats.lastRun)}
          </p>
        </Card>

        <Card className="border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
          <p className="flex items-center text-xs text-stone-500 uppercase tracking-wide">
            Total Proposals
            <InfoTip text="Cumulative count of all skill-improvement proposals ever generated by the APO, including both pending and archived. Reflects the total volume of optimizations the system has identified." />
          </p>
          <p className="mt-1 text-3xl font-bold text-slate-950">
            {stats.totalProposals}
          </p>
        </Card>

        <Card className="border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
          <p className="flex items-center text-xs text-stone-500 uppercase tracking-wide">
            Pending
            <InfoTip text="Proposals awaiting your review. Each one suggests a specific edit to a skill file to improve agent behavior. Review them in the Proposals list below and accept or dismiss." />
          </p>
          <p className="mt-1 text-3xl font-bold text-amber-700">
            {stats.pendingProposals}
          </p>
        </Card>

        <Card className="border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
          <p className="flex items-center text-xs text-stone-500 uppercase tracking-wide">
            Queued
            <InfoTip text="Approved proposals waiting for the Agent Lightning worker CLI to implement them. By default, queued work is assigned to qwen unless the operator overrides the executor CLI." />
          </p>
          <p className="mt-1 text-3xl font-bold text-cyan-700">
            {stats.approvedProposals}
          </p>
        </Card>

        <Card className="border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
          <p className="flex items-center text-xs text-stone-500 uppercase tracking-wide">
            Archived
            <InfoTip text="Proposals that have been accepted (applied to skill files) or dismissed. Archived proposals are kept for audit history so you can track what optimizations have been applied over time." />
          </p>
          <p className="mt-1 text-3xl font-bold text-stone-600">
            {stats.archivedProposals}
          </p>
        </Card>
      </div>

      <div className="rounded-md border border-slate-200 bg-white/85 p-4 shadow-[0_12px_32px_rgba(15,23,42,0.04)]">
        <div className="grid gap-3 md:grid-cols-3">
          {stages.map((stage) => (
            <div key={stage.label} className="min-w-0">
              <div className="mb-2 flex items-center justify-between gap-2">
                <div>
                  <p className="text-xs font-semibold uppercase text-slate-700">
                    {stage.label}
                  </p>
                  <p className="text-xs text-stone-500">{stage.description}</p>
                </div>
                <p className="text-lg font-bold text-slate-950">{stage.count}</p>
              </div>
              <div className="h-1.5 rounded-full bg-slate-200">
                <div
                  className={`h-1.5 rounded-full ${stage.tone}`}
                  style={{ width: stage.count > 0 ? "100%" : "12%" }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
