"use client";

import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import type { ApoProposal, ApoProposalTracking } from "@/types";

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function trackingTone(status: ApoProposal["status"]) {
  if (status === "pending") return "border-amber-200 bg-amber-50";
  if (status === "approved") return "border-cyan-200 bg-cyan-50";
  return "border-emerald-200 bg-emerald-50";
}

function fallbackTracking(proposal: ApoProposal): ApoProposalTracking {
  if (proposal.status === "pending") {
    return {
      phase: "pending",
      label: "Awaiting review",
      description: "Generated by APO and waiting for operator approval.",
      timestamp: proposal.timestamp,
    };
  }
  if (proposal.status === "approved") {
    return {
      phase: "queued",
      label: "Queued for worker",
      description: "Approved and waiting for the worker.",
      timestamp: proposal.timestamp,
    };
  }
  return {
    phase: "implemented",
    label: "Archived",
    description: "Archived for audit history.",
    timestamp: proposal.timestamp,
  };
}

interface ProposalDetailProps {
  proposal: ApoProposal | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ProposalDetail({
  proposal,
  open,
  onOpenChange,
}: ProposalDetailProps) {
  if (!proposal) return null;

  const isPending = proposal.status === "pending";
  const isApproved = proposal.status === "approved";
  const tracking = proposal.tracking ?? fallbackTracking(proposal);

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="flex w-[480px] flex-col border-slate-200 bg-white text-slate-950 sm:max-w-[480px]"
      >
        <SheetHeader className="shrink-0 border-b border-slate-200 pb-4">
          <div className="flex items-start gap-2 flex-wrap">
            <Badge
              variant="outline"
              className={
                isPending
                  ? "border-amber-300 text-amber-700 text-xs"
                  : isApproved
                    ? "border-cyan-300 text-cyan-700 text-xs"
                  : "border-slate-300 text-stone-600 text-xs"
              }
            >
              {isApproved ? "queued" : proposal.status}
            </Badge>
            <Badge
              variant="outline"
              className="border-slate-300 text-stone-600 text-xs"
            >
              {proposal.subsystem}
            </Badge>
          </div>
          <SheetTitle className="mt-1 text-base leading-snug text-slate-950">
            {proposal.skill}
          </SheetTitle>
          <SheetDescription className="text-xs text-stone-500">
            {formatDateTime(proposal.timestamp)} &middot; {proposal.filename}
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          <div className={`rounded-md border p-3 ${trackingTone(proposal.status)}`}>
            <p className="text-xs font-semibold text-slate-950">{tracking.label}</p>
            <p className="mt-1 text-xs leading-relaxed text-stone-600">
              {tracking.description}
            </p>
            <dl className="mt-3 grid grid-cols-1 gap-2 text-xs sm:grid-cols-2">
              <div>
                <dt className="text-stone-500">Status time</dt>
                <dd className="text-slate-700">{formatDateTime(tracking.timestamp)}</dd>
              </div>
              {tracking.executorCli && (
                <div>
                  <dt className="text-stone-500">Executor</dt>
                  <dd className="text-slate-700">{tracking.executorCli}</dd>
                </div>
              )}
              {tracking.targetKind && (
                <div>
                  <dt className="text-stone-500">Target</dt>
                  <dd className="text-slate-700">{tracking.targetKind}</dd>
                </div>
              )}
              {tracking.applied !== undefined && (
                <div>
                  <dt className="text-stone-500">Worker result</dt>
                  <dd className="text-slate-700">
                    {tracking.applied ? "Applied" : "Already present"}
                  </dd>
                </div>
              )}
            </dl>
            {tracking.targetPath && (
              <p className="mt-3 break-all text-xs text-stone-500">{tracking.targetPath}</p>
            )}
          </div>
          <pre className="whitespace-pre-wrap break-words font-mono text-xs leading-relaxed text-slate-700">
            {proposal.content}
          </pre>
        </div>
      </SheetContent>
    </Sheet>
  );
}
